lowering-whitelist

diff --git a/.github/workflows/before_merge.yaml b/.github/workflows/before_merge.yaml
--- a/.github/workflows/before_merge.yaml
+++ b/.github/workflows/before_merge.yaml
@@ -18,38 +18,38 @@ permissions:
   pull-requests: write
 
 jobs:
-  tools-tests:
-    env:
-      pytest_verbosity: 2    
-      pytest_report_title: "⭐️ Tools Tests"
-    runs-on: ["in-service"]
-    steps:      
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/common_repo_setup        
-      - name: Run Tools Tests 
-        run: |
-          python3 -m pytest --github-report tests/tools/ -s
+  # tools-tests:
+  #   env:
+  #     pytest_verbosity: 2    
+  #     pytest_report_title: "⭐️ Tools Tests"
+  #   runs-on: ["in-service"]
+  #   steps:      
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/common_repo_setup        
+  #     - name: Run Tools Tests 
+  #       run: |
+  #         python3 -m pytest --github-report tests/tools/ -s
 
-  lowering-tests:
-    runs-on: ["in-service"]
-    env:
-      pytest_verbosity: 2    
-      pytest_report_title: "⭐️ Aten → TTNN Lowering Tests"
-    strategy:
-      matrix: # Need to find a way to replace this with a generator
-        group: [1, 2]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/common_repo_setup
+  # lowering-tests:
+  #   runs-on: ["in-service"]
+  #   env:
+  #     pytest_verbosity: 2    
+  #     pytest_report_title: "⭐️ Aten → TTNN Lowering Tests"
+  #   strategy:
+  #     matrix: # Need to find a way to replace this with a generator
+  #       group: [1, 2]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/common_repo_setup
 
-      - name: Run Lowering Tests 
-        run: |
-          python3 -m pytest --github-report tests/lowering/ --splits 2 --group ${{ matrix.group }} -s
+  #     - name: Run Lowering Tests 
+  #       run: |
+  #         python3 -m pytest --github-report tests/lowering/ --splits 2 --group ${{ matrix.group }} -s
 
   model-tests:
-    needs: lowering-tests
     runs-on: ["in-service"]
     strategy:
+      fail-fast: false
       matrix: # Need to find a way to replace this with a generator
         group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
 
@@ -85,6 +85,7 @@ jobs:
           ls -l
           cd ..
           exit 0;
+        continue-on-error: true
 
       - name: Upload Metrics Artifact
         if: success()  # Only run if tests passed
@@ -93,39 +94,39 @@ jobs:
           name: model-tests-metrics-group-${{ matrix.group }}
           path: metrics/
 
-  model-autogen-op-tests:
-    needs: lowering-tests
-    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_report != 'None'}}
-    runs-on: ["in-service"]
-    strategy:
-      matrix: # Need to find a way to replace this with a generator
-        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
+  # model-autogen-op-tests:
+  #   needs: lowering-tests
+  #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_report != 'None'}}
+  #   runs-on: ["in-service"]
+  #   strategy:
+  #     matrix: # Need to find a way to replace this with a generator
+  #       group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
 
-    env:
-      pytest_verbosity: 0
-      pytest_report_title: "⭐️ Model Input Variations Tests - Group ${{ matrix.group }}"
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/common_repo_setup
+  #   env:
+  #     pytest_verbosity: 0
+  #     pytest_report_title: "⭐️ Model Input Variations Tests - Group ${{ matrix.group }}"
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/common_repo_setup
 
-      - name: Run Model Input Variations Tests
-        run: |
-          set +e
-          rm -rf tests/autogen-op/ALL
-          python3 -m pytest --github-report tests/autogen-op -s
-          exit_code=$?  # Capture the exit code, but ignore any errors for now.
-          ls -l
-          cd metrics-autogen-op
-          ls -l
-          cd ..
-          exit 0;
+  #     - name: Run Model Input Variations Tests
+  #       run: |
+  #         set +e
+  #         rm -rf tests/autogen-op/ALL
+  #         python3 -m pytest --github-report tests/autogen-op -s
+  #         exit_code=$?  # Capture the exit code, but ignore any errors for now.
+  #         ls -l
+  #         cd metrics-autogen-op
+  #         ls -l
+  #         cd ..
+  #         exit 0;
 
-      - name: Upload Input Variations Metrics Artifact
-        if: success()  # Only run if tests passed
-        uses: actions/upload-artifact@v4
-        with:
-          name: model-autogen-op-tests-metrics-group-${{ matrix.group }}
-          path: metrics-autogen-op/
+  #     - name: Upload Input Variations Metrics Artifact
+  #       if: success()  # Only run if tests passed
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: model-autogen-op-tests-metrics-group-${{ matrix.group }}
+  #         path: metrics-autogen-op/
 
   collect-model-artifacts-from-matrix-jobs:
     needs: model-tests
@@ -150,137 +151,137 @@ jobs:
           name: model-tests-metrics
           path: metrics/
 
-  collect-op-artifacts-from-matrix-jobs:
-    needs: model-autogen-op-tests
-    runs-on: ["in-service"]
-    env:
-      pytest_verbosity: 0
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/common_repo_setup
+  # collect-op-artifacts-from-matrix-jobs:
+  #   needs: model-autogen-op-tests
+  #   runs-on: ["in-service"]
+  #   env:
+  #     pytest_verbosity: 0
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/common_repo_setup
 
-      - name: Download All Input Variations Metrics Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: model-autogen-op-tests-metrics-group-*
-          merge-multiple: true
-          path: metrics-autogen-op/
+  #     - name: Download All Input Variations Metrics Artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: model-autogen-op-tests-metrics-group-*
+  #         merge-multiple: true
+  #         path: metrics-autogen-op/
 
-      - name: Upload Input Variations Metrics Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: model-autogen-op-tests-metrics
-          path: metrics-autogen-op/
+  #     - name: Upload Input Variations Metrics Artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: model-autogen-op-tests-metrics
+  #         path: metrics-autogen-op/
 
-  collect-metrics:
-    needs: [model-tests, model-autogen-op-tests]
-    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_report != 'None'}}
-    runs-on: ["in-service"]
-    env:
-      PYTHONPATH: ${{ github.workspace }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/common_repo_setup
+  # collect-metrics:
+  #   needs: [model-tests, model-autogen-op-tests]
+  #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_report != 'None'}}
+  #   runs-on: ["in-service"]
+  #   env:
+  #     PYTHONPATH: ${{ github.workspace }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/common_repo_setup
 
-      - name: Download All Metrics Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: model-tests-metrics-group-*
-          merge-multiple: true
-          path: metrics/
+  #     - name: Download All Metrics Artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: model-tests-metrics-group-*
+  #         merge-multiple: true
+  #         path: metrics/
 
-      - name: Download All Input Variations Metrics Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: model-autogen-op-tests-metrics-group-*
-          merge-multiple: true
-          path: metrics-autogen-op/
-      # - name: Download Metrics Artifacts
-      #   env:
-      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
-      #     GH_REPO: ${{ github.repository }}
-      #   run: |
-      #     mkdir -p metrics
-      #     for i in $(seq 1 40); do
-      #       echo "Downloading metrics for Group $i"
-      #       gh run download ${{ github.run_id }} --name "model-tests-metrics-group-$i" --dir metrics/
-      #       cd metrics
-      #       ls -l
-      #       cd ..
-      #     done
+  #     - name: Download All Input Variations Metrics Artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: model-autogen-op-tests-metrics-group-*
+  #         merge-multiple: true
+  #         path: metrics-autogen-op/
+  #     # - name: Download Metrics Artifacts
+  #     #   env:
+  #     #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
+  #     #     GH_REPO: ${{ github.repository }}
+  #     #   run: |
+  #     #     mkdir -p metrics
+  #     #     for i in $(seq 1 40); do
+  #     #       echo "Downloading metrics for Group $i"
+  #     #       gh run download ${{ github.run_id }} --name "model-tests-metrics-group-$i" --dir metrics/
+  #     #       cd metrics
+  #     #       ls -l
+  #     #       cd ..
+  #     #     done
 
-      - name: Collect Metrics Report
-        run: |
-          python3 tools/collect_metrics.py
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
+  #     - name: Collect Metrics Report
+  #       run: |
+  #         python3 tools/collect_metrics.py
+  #         git config user.name "GitHub Actions"
+  #         git config user.email "actions@github.com"
 
-          if [ "${{ github.event.inputs.commit_report }}" == "All" ]; then
-            git add --all
-          elif [ "${{ github.event.inputs.commit_report }}" == "Docs" ]; then
-            git add README.md
-            git add docs/
-          elif [ "${{ github.event.inputs.commit_report }}" == "None" ]; then
-            echo "No files will be committed"
-            exit 0
-          fi
+  #         if [ "${{ github.event.inputs.commit_report }}" == "All" ]; then
+  #           git add --all
+  #         elif [ "${{ github.event.inputs.commit_report }}" == "Docs" ]; then
+  #           git add README.md
+  #           git add docs/
+  #         elif [ "${{ github.event.inputs.commit_report }}" == "None" ]; then
+  #           echo "No files will be committed"
+  #           exit 0
+  #         fi
 
-          if git diff-index --quiet HEAD; then
-            echo "No changes to commit"
-          else
-            git commit -m '[auto][on-merge-queue] Update metrics report in README.md'
-            git push
-          fi
+  #         if git diff-index --quiet HEAD; then
+  #           echo "No changes to commit"
+  #         else
+  #           git commit -m '[auto][on-merge-queue] Update metrics report in README.md'
+  #           git push
+  #         fi
 
-  push-autogen-op-tests:
-    needs: model-autogen-op-tests
-    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_report != 'None'}}
-    runs-on: ["in-service"]
-    env:
-      PYTHONPATH: ${{ github.workspace }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/common_repo_setup
+  # push-autogen-op-tests:
+  #   needs: model-autogen-op-tests
+  #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_report != 'None'}}
+  #   runs-on: ["in-service"]
+  #   env:
+  #     PYTHONPATH: ${{ github.workspace }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/common_repo_setup
 
-      - name: Remove current autogen-op tests
-        run: |
-          rm -rf tests/autogen-op/
-          exit 0
+  #     - name: Remove current autogen-op tests
+  #       run: |
+  #         rm -rf tests/autogen-op/
+  #         exit 0
 
-      - name: Download All Input Variations Tests Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: model-autogen-op-tests-group-*
-          merge-multiple: true
-          path: tests/autogen-op/
+  #     - name: Download All Input Variations Tests Artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: model-autogen-op-tests-group-*
+  #         merge-multiple: true
+  #         path: tests/autogen-op/
 
-      - name: Collect Metrics Report
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-          echo "Remove these files because it's heavy for running"
-          rm -f tests/autogen-op/Stable_Diffusion_V2/test_Stable_Diffusion_V2_aten_convolution_default.py
-          rm -f tests/autogen-op/ALL/test_ALL_aten_convolution_default.py
-          rm -f tests/autogen-op/ALL/test_ALL_aten_convolution_backward_default.py
-          if [ "${{ github.event.inputs.commit_report }}" == "All" ]; then
-            git add --all
-          elif [ "${{ github.event.inputs.commit_report }}" == "Tests" ]; then
-            git add tests/
-          elif [ "${{ github.event.inputs.commit_report }}" == "None" ]; then
-            echo "No files will be committed"
-            exit 0
-          fi
-          if git diff-index --quiet HEAD; then
-            echo "No changes to commit"
-          else
-            git commit -m '[auto][on-merge-queue] Update input variations tests'
-            git push
-          fi
+  #     - name: Collect Metrics Report
+  #       run: |
+  #         git config user.name "GitHub Actions"
+  #         git config user.email "actions@github.com"
+  #         echo "Remove these files because it's heavy for running"
+  #         rm -f tests/autogen-op/Stable_Diffusion_V2/test_Stable_Diffusion_V2_aten_convolution_default.py
+  #         rm -f tests/autogen-op/ALL/test_ALL_aten_convolution_default.py
+  #         rm -f tests/autogen-op/ALL/test_ALL_aten_convolution_backward_default.py
+  #         if [ "${{ github.event.inputs.commit_report }}" == "All" ]; then
+  #           git add --all
+  #         elif [ "${{ github.event.inputs.commit_report }}" == "Tests" ]; then
+  #           git add tests/
+  #         elif [ "${{ github.event.inputs.commit_report }}" == "None" ]; then
+  #           echo "No files will be committed"
+  #           exit 0
+  #         fi
+  #         if git diff-index --quiet HEAD; then
+  #           echo "No changes to commit"
+  #         else
+  #           git commit -m '[auto][on-merge-queue] Update input variations tests'
+  #           git push
+  #         fi
 
   validate-pr:
     if: ${{ always() }}
     runs-on: ubuntu-latest    
-    needs: [model-tests, tools-tests, lowering-tests, collect-metrics]
+    needs: model-tests
     steps:
       - run: |
           model_result="${{ needs.model-tests.result}}"
