Edit input variation CI strategy and support generate merged input var tests

diff --git a/.github/workflows/before_merge.yaml b/.github/workflows/before_merge.yaml
--- a/.github/workflows/before_merge.yaml
+++ b/.github/workflows/before_merge.yaml
@@ -91,7 +91,6 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: model-tests-metrics-group-${{ matrix.group }}
-          merge-multiple: true
           path: metrics/
 
   model-autogen-op-tests:
@@ -108,10 +107,11 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/common_repo_setup
 
-      - name: Download Metrics Artifacts for Generate Input Variations Tests
+      - name: Download All Metrics Artifacts for Generate Input Variations Tests
         uses: actions/download-artifact@v4
         with:
-          pattern: model-tests-metrics-group-${{ matrix.group }}
+          pattern: model-tests-metrics-group-*
+          merge-multiple: true
           path: metrics/
       - name: Run Model Input Variations Tests
         run: |
@@ -123,20 +123,13 @@ jobs:
             echo "Failed to generate input variation test : exit code $exit_code.";
             exit 1;  # Fail the workflow for other errors
           fi
-          python3 -m pytest --github-report tests/autogen-op -s
+          python3 -m pytest --github-report tests/autogen-op/ --splits 40 --group ${{ matrix.group }} -s
           exit_code=$?  # Capture the exit code, but ignore any errors for now.
           ls -l
           cd metrics-autogen-op
           ls -l
           cd ..
           exit 0;
-
-      - name: Upload Input Variations Tests Artifact
-        if: success()  # Only run if tests passed
-        uses: actions/upload-artifact@v4
-        with:
-          name: model-autogen-op-tests-group-${{ matrix.group }}
-          path: tests/autogen-op/
 
       - name: Upload Input Variations Metrics Artifact
         if: success()  # Only run if tests passed
@@ -161,19 +154,33 @@ jobs:
           merge-multiple: true
           path: metrics/
 
-      - name: Download All Input Variations Tests Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: model-autogen-op-tests-group-*
-          merge-multiple: true
-          path: tests/autogen-op/
-
       - name: Download All Input Variations Metrics Artifacts
         uses: actions/download-artifact@v4
         with:
           pattern: model-autogen-op-tests-metrics-group-*
           merge-multiple: true
           path: metrics-autogen-op/
+
+      - name: Generate Model Input Variations Tests
+        run: |
+          set +e
+          rm -rf tests/autogen-op/
+          python3 tools/generate_input_variation_test_from_models.py
+          exit_code=$?  # Capture the exit code
+          if [ $exit_code -ne 0 ]; then
+            echo "Failed to generate input variation test : exit code $exit_code.";
+            exit 1;  # Fail the workflow for other errors
+          fi
+          python3 tools/generate_input_variation_test_from_models.py --merge=True
+          exit_code=$?  # Capture the exit code
+          if [ $exit_code -ne 0 ]; then
+            echo "Failed to generate input variation test all : exit code $exit_code.";
+            exit 1;  # Fail the workflow for other errors
+          fi
+          cd metrics-autogen-op
+          ls -l
+          cd ..
+          exit 0;
 
       - name: Upload Metrics Artifact
         if: success()  # Only run if tests passed
@@ -269,8 +276,7 @@ jobs:
       - name: Download All Input Variations Tests Artifacts
         uses: actions/download-artifact@v4
         with:
-          pattern: model-autogen-op-tests-group-*
-          merge-multiple: true
+          pattern: model-autogen-op-tests
           path: tests/autogen-op/
 
       - name: Collect Metrics Report
